/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.userregistrationtesting;

import java.util.regex.Pattern;

public class UserRegistration {
	
	public static boolean validatetName(String name) {
		return Pattern.matches("^[A-Z][A-Za-z]{2,}$",name);
	}
	
	public static boolean validateLasttName(String lastName) {
		return Pattern.matches("^[A-Z][A-Za-z]{2,}$", lastName);
	}
	
	public static boolean validateEmail(String emailId) {
		return Pattern.matches("^[a-zA-Z][a-zA-Z0-9]*[a-zA-Z0-9]([+-_.][a-zA-Z]*)?@[a-zA-Z0-9]*[.][a-z]{2,4}([.][a-zA-z]{2})?$", emailId);
	}
	
	public static boolean validatePhoneNumber(String phoneNumber) {
		return  Pattern.matches("^[0-9]{2}[ ][1-9][0-9]{9}$", phoneNumber);
	}
	public static boolean validatePassword(String password) {
		return Pattern.matches("(?=.*?[A-Z])(?=.*?[0-9])(?=.*[#?!@$%^&*-]).{8,}$", password);
	}

}
